//go:build ignore

// Regenerate with go generate ./internal/analyzerplugin after reviewing a
// grammar dependency change. This runs only during development, never analysis.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	b, err := exec.Command("go", "list", "-m", "-json", "github.com/tree-sitter/tree-sitter-typescript").Output()
	if err != nil {
		return err
	}
	var module struct {
		Version string
		Dir     string
		Sum     string
		Replace *json.RawMessage
	}
	if err := json.Unmarshal(b, &module); err != nil {
		return err
	}
	if module.Replace != nil || module.Version == "" || module.Sum == "" || module.Dir == "" {
		return fmt.Errorf("grammar generation requires a pinned, unreplaced module")
	}
	h := sha256.New()
	for _, logical := range []string{"tsx/src/parser.c", "tsx/src/scanner.c", "typescript/src/parser.c", "typescript/src/scanner.c"} {
		b, err := os.ReadFile(filepath.Join(module.Dir, filepath.FromSlash(logical)))
		if err != nil {
			return err
		}
		_, _ = h.Write([]byte(logical))
		_, _ = h.Write([]byte{0})
		_, _ = h.Write(b)
		_, _ = h.Write([]byte{0})
	}
	source := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage analyzerplugin\n\nconst (\n pinnedGrammarVersion = %q\n pinnedGrammarModuleSum = %q\n pinnedGrammarDigest = %q\n)\n", module.Version, module.Sum, hex.EncodeToString(h.Sum(nil)))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return err
	}
	return os.WriteFile("grammar_identity_generated.go", formatted, 0o644)
}
