// Code generated by go generate; DO NOT EDIT.

package analyzerplugin

const (
	pinnedGrammarVersion   = "v0.23.2"
	pinnedGrammarModuleSum = "h1:/Odvphn18PniVixb9e97X0DbNVsU6Qocv9mfkyzdXwU="
	pinnedGrammarDigest    = "fa78aecad69d67d7e9d79705448cbb41d6c52fd3a7192c12914441d3f9c62c54"
)
